spring:
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:~/spring-oauth2db
    username: sa
    password:
    schema: classpath:oauth-schema.sql
    initialization-mode: always
    type: com.zaxxer.hikari.HikariDataSource
    data:
      - classpath:oauth2-data.sql
  jpa:
    database: H2
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: create-drop
    open-in-view: false
  main:
    # 允许覆盖 OAuth2 放在容器中的 Bean 对象
    allow-bean-definition-overriding: true
  h2:
    console:
      enabled: true
logging:
  level:
    root: debug
